"""Training / inference backend adapters."""

from __future__ import annotations

from pathlib import Path

from llmbench.catalog import ModelEntry
from llmbench.config import BenchConfig
from llmbench.platform_info import PlatformInfo


class BackendError(RuntimeError):
    pass


def ensure_dataset(path: Path) -> None:
    if not path.exists():
        raise BackendError(f"Dataset not found: {path}")
    if path.suffix.lower() != ".jsonl":
        raise BackendError("Dataset must be a .jsonl file (instruction/input/output).")


def train_with_transformers(
    cfg: BenchConfig,
    model: ModelEntry,
    method: str,
    info: PlatformInfo,
) -> Path:
    """LoRA/QLoRA via Hugging Face transformers + peft + trl."""
    try:
        import torch
        from datasets import load_dataset
        from peft import LoraConfig
        from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
        from trl import SFTConfig, SFTTrainer
    except ImportError as exc:
        raise BackendError(
            "CUDA/transformers stack missing. Install with:\n"
            "  pip install 'llmbench[cuda]'\n"
            "On Windows prefer WSL2. See README."
        ) from exc

    ensure_dataset(cfg.dataset)
    if info.accel != "cuda":
        raise BackendError(
            f"transformers training backend expects CUDA (detected: {info.accel}). "
            "On Mac use backend=mlx."
        )

    cfg.output_dir.mkdir(parents=True, exist_ok=True)
    tokenizer = AutoTokenizer.from_pretrained(model.hf_id, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    quant = None
    torch_dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    if method == "qlora":
        quant = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch_dtype,
            bnb_4bit_use_double_quant=True,
        )

    llm = AutoModelForCausalLM.from_pretrained(
        model.hf_id,
        quantization_config=quant,
        torch_dtype=torch_dtype if quant is None else None,
        device_map="auto",
        trust_remote_code=True,
    )

    peft_config = LoraConfig(
        r=cfg.train.lora_r,
        lora_alpha=cfg.train.lora_alpha,
        lora_dropout=cfg.train.lora_dropout,
        bias="none",
        task_type="CAUSAL_LM",
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    )

    ds = load_dataset("json", data_files=str(cfg.dataset), split="train")

    def formatting(example: dict) -> str:
        instruction = example.get("instruction", "")
        user = example.get("input", "")
        output = example.get("output", "")
        if user:
            prompt = f"### Instruction:\n{instruction}\n\n### Input:\n{user}\n\n### Response:\n"
        else:
            prompt = f"### Instruction:\n{instruction}\n\n### Response:\n"
        return prompt + output

    sft = SFTConfig(
        output_dir=str(cfg.output_dir),
        num_train_epochs=cfg.train.epochs,
        per_device_train_batch_size=cfg.train.batch_size,
        gradient_accumulation_steps=cfg.train.grad_accum,
        learning_rate=cfg.train.learning_rate,
        logging_steps=1,
        save_strategy="epoch",
        max_seq_length=cfg.train.max_seq_len,
        packing=False,
        report_to=[],
    )

    trainer = SFTTrainer(
        model=llm,
        args=sft,
        train_dataset=ds,
        peft_config=peft_config,
        processing_class=tokenizer,
        formatting_func=formatting,
    )
    trainer.train()
    adapter_dir = cfg.output_dir / "adapter"
    trainer.model.save_pretrained(adapter_dir)
    tokenizer.save_pretrained(adapter_dir)
    return adapter_dir


def train_with_mlx(cfg: BenchConfig, model: ModelEntry, info: PlatformInfo) -> Path:
    """Apple Silicon LoRA via mlx-lm. Falls back to a clear install / dry-run message."""
    ensure_dataset(cfg.dataset)
    if info.os != "mac":
        raise BackendError("MLX training is only available on macOS (Apple Silicon).")

    try:
        import mlx.core  # noqa: F401
    except ImportError as exc:
        raise BackendError(
            "MLX not installed. On Apple Silicon run:\n  pip install 'llmbench[mlx]'"
        ) from exc

    cfg.output_dir.mkdir(parents=True, exist_ok=True)
    # mlx-lm's fine-tune entrypoints evolve; shell out to the documented CLI when present,
    # otherwise write a runnable script the user can invoke.
    script = cfg.output_dir / "mlx_train_command.sh"
    adapter_dir = cfg.output_dir / "adapter"
    cmd = (
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        f"# Generated by llmbench for {model.id}\n"
        "python -m mlx_lm lora \\\n"
        f"  --model {model.hf_id} \\\n"
        f"  --train \\\n"
        f"  --data {cfg.dataset} \\\n"
        f"  --batch-size {cfg.train.batch_size} \\\n"
        f"  --lora-layers 16 \\\n"
        f"  --iters {max(50, cfg.train.epochs * 50)} \\\n"
        f"  --adapter-path {adapter_dir}\n"
    )
    script.write_text(cmd, encoding="utf-8")
    script.chmod(0o755)

    # Try running if mlx_lm.lora module exists
    try:
        import subprocess
        import sys

        result = subprocess.run(
            [
                sys.executable,
                "-m",
                "mlx_lm",
                "lora",
                "--model",
                model.hf_id,
                "--train",
                "--data",
                str(cfg.dataset),
                "--batch-size",
                str(cfg.train.batch_size),
                "--lora-layers",
                "16",
                "--iters",
                str(max(50, cfg.train.epochs * 50)),
                "--adapter-path",
                str(adapter_dir),
            ],
            check=False,
        )
        if result.returncode == 0:
            return adapter_dir
    except Exception:
        pass

    raise BackendError(
        "MLX LoRA needs a dataset layout mlx-lm expects (or a newer mlx-lm).\n"
        f"A helper script was written to: {script}\n"
        "Convert data if needed, then run that script. "
        "See https://github.com/ml-explore/mlx-lm"
    )


def train_with_unsloth(cfg: BenchConfig, model: ModelEntry, info: PlatformInfo) -> Path:
    if info.accel != "cuda":
        raise BackendError("Unsloth requires NVIDIA CUDA.")
    try:
        from unsloth import FastLanguageModel  # noqa: F401
    except ImportError as exc:
        raise BackendError(
            "Unsloth is optional and not installed.\n"
            "Install from https://github.com/unslothai/unsloth then re-run,\n"
            "or set backend: transformers in config.yaml"
        ) from exc
    # Keep portable path as default; Unsloth users can extend this adapter.
    raise BackendError(
        "Unsloth adapter is scaffolded. For now use backend: transformers "
        "(same LoRA/QLoRA flow, wider install compatibility)."
    )


def run_train(cfg: BenchConfig, model: ModelEntry, backend: str, method: str, info: PlatformInfo) -> Path:
    if backend == "transformers":
        return train_with_transformers(cfg, model, method, info)
    if backend == "mlx":
        return train_with_mlx(cfg, model, info)
    if backend == "unsloth":
        return train_with_unsloth(cfg, model, info)
    raise BackendError(f"Unknown training backend: {backend}")
